### ISSUE TITLE
Integration stops working with Home Assistant Core Update 2024.7.4

### ISSUE THREAD

**Issue by Gerti1972** [h4de5/home-assistant-toshiba_ac#195]
In my case the integration stops working with Home Assistant Core Update 2024.7.4

**Comment by chrisandsally** [comment]
Works for me on 2024.7.4

**Comment by Gerti1972** [comment]
I tried the Update again and now it also works for me. I'm wondering why it doesn't work on first try.

**Comment by manuvbv** [comment]
I have the same problem here, the integration stop working, when I reboot my HA it works but after few times, it stops working :(
I just found that when I recharge the integration it works again. I will tell you if it stops working again.
Thanks

**Comment by Kheperu** [comment]
Same problem here.
It says the entity is no longer being provided by the toshiba_ac integration.

**Comment by rankxaroth** [comment]
I have the same problem. Usually helps to reload the integration and it works again, but after some time it stops working.

**Comment by KaSroka** [comment]
Please try with latest version of the integration, stability should be improved.

**Comment by h4de5** [comment]
closing as most probably fixed in #199

**Comment by gvamporov** [comment]
Not sure if this is the same problem, but after the update to 2024.7.4, the integration works OK for some time and after that i get:
`Failed to call service climate/set_hvac_mode. Credentials invalid, could not connect`
and i can not change any option on my devices...
Reloading it again temporary fixes the problem.
I did not encounter such problems before the update...

**Comment by h4de5** [comment]
can you chek if there are other errors in logs?

**Comment by alex156** [comment]
i also still have the same problem. it lasts longer now, but after 2 days it fails. after restart the integration, it now works again

HA 2024.8.1

![image](https://github.com/user-attachments/assets/7c03255f-c9b7-43e1-863a-d9113c0b55b2)

**Comment by rankxaroth** [comment]
> can you chek if there are other errors in logs?

There is not much more in the logs, it seems that the credentials somehow expired.

Logger: homeassistant.core
Zdroj: core.py:2783
První výskyt: 12:23:02 (7 výskyty)
Naposledy logováno: 22:51:23

Error executing service: <ServiceCall climate.set_hvac_mode (c:01J5JSVHGAV5N7C232PKGEB7ZF): entity_id=['climate.jakub'], hvac_mode=cool>
Error executing service: <ServiceCall climate.set_temperature (c:01J5JSVK946H4ATC9DNRSS3QV0): entity_id=['climate.jidelna'], temperature=20.0>
Error executing service: <ServiceCall climate.set_temperature (c:01J5JSVKTMJS8X7KMQPTRBSMHM): entity_id=['climate.jakub'], temperature=23.0>
Error executing service: <ServiceCall climate.set_hvac_mode (c:01J5K7PYRYBDYRQ4AGMF4N6QPS): entity_id=['climate.loznice'], hvac_mode=off>
Error executing service: <ServiceCall climate.set_hvac_mode (c:01J5KM4JNNXD02HJXFBW4903WQ): entity_id=['climate.jidelna'], hvac_mode=off>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/azure/iot/device/iothub/aio/async_clients.py", line 36, in handle_result
    return await callback.completion()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/azure/iot/device/common/async_adapter.py", line 91, in completion
    return await self.future
           ^^^^^^^^^^^^^^^^^
azure.iot.device.common.transport_exceptions.UnauthorizedError: Connection Refused: not authorised.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 2783, in _run_service_call_catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 2806, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 999, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1071, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/toshiba_ac/climate.py", line 194, in async_set_hvac_mode
    await self._device.set_ac_status(ToshibaAcStatus.OFF)
  File "/usr/local/lib/python3.12/site-packages/toshiba_ac/device/__init__.py", line 269, in set_ac_status
    await self.send_state_to_ac(state)
  File "/usr/local/lib/python3.12/site-packages/toshiba_ac/device/__init__.py", line 259, in send_state_to_ac
    await self.amqp_api.send_message(str(fcu_to_ac))
  File "/usr/local/lib/python3.12/site-packages/toshiba_ac/utils/amqp_api.py", line 100, in send_message
    await self.device.send_message(msg)
  File "/usr/local/lib/python3.12/site-packages/azure/iot/device/aio/patch_documentation.py", line 60, in send_message
    return await super(IoTHubDeviceClient, self).send_message(message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/azure/iot/device/iothub/aio/async_clients.py", line 359, in send_message
    await handle_result(callback)
  File "/usr/local/lib/python3.12/site-packages/azure/iot/device/iothub/aio/async_clients.py", line 44, in handle_result
    raise exceptions.CredentialError("Credentials invalid, could not connect") from e
azure.iot.device.exceptions.CredentialError: Credentials invalid, could not connect

**Comment by gvamporov** [comment]
Hi
I also updated to latest HA (2024.8.2) and i still continue to see the same behavior.
Here is what i see in log, when the integration stops working (again, after reloading the integration everything is back to normal):

2024-08-24 07:28:19.241 WARNING (pipeline) [azure.iot.device.common.pipeline.pipeline_stages_base] ConnectionStateStage: DisconnectEvent received while in unexpected state - ConnectionState.DISCONNECTED
2024-08-24 07:28:19.243 WARNING (callback) [azure.iot.device.common.handle_exceptions] Exception caught in background thread.  Unable to handle.
2024-08-24 07:28:19.243 WARNING (callback) [azure.iot.device.common.handle_exceptions] ['azure.iot.device.common.transport_exceptions.ConnectionDroppedError: Unexpected disconnection\n']
2024-08-24 07:28:19.239 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [3510919208] Unexpected exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/azure/iot/device/iothub/aio/async_clients.py", line 36, in handle_result
    return await callback.completion()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/azure/iot/device/common/async_adapter.py", line 91, in completion
    return await self.future
           ^^^^^^^^^^^^^^^^^
azure.iot.device.common.transport_exceptions.UnauthorizedError: Connection Refused: not authorised.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 241, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2763, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2806, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 999, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1071, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/toshiba_ac/climate.py", line 197, in async_set_hvac_mode
    await self._device.set_ac_status(ToshibaAcStatus.ON)
  File "/usr/local/lib/python3.12/site-packages/toshiba_ac/device/__init__.py", line 269, in set_ac_status
    await self.send_state_to_ac(state)
  File "/usr/local/lib/python3.12/site-packages/toshiba_ac/device/__init__.py", line 259, in send_state_to_ac
    await self.amqp_api.send_message(str(fcu_to_ac))
  File "/usr/local/lib/python3.12/site-packages/toshiba_ac/utils/amqp_api.py", line 100, in send_message
    await self.device.send_message(msg)
  File "/usr/local/lib/python3.12/site-packages/azure/iot/device/aio/patch_documentation.py", line 60, in send_message
    return await super(IoTHubDeviceClient, self).send_message(message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/azure/iot/device/iothub/aio/async_clients.py", line 359, in send_message
    await handle_result(callback)
  File "/usr/local/lib/python3.12/site-packages/azure/iot/device/iothub/aio/async_clients.py", line 44, in handle_result
    raise exceptions.CredentialError("Credentials invalid, could not connect") from e
azure.iot.device.exceptions.CredentialError: Credentials invalid, could not connect
